Added code in HackerRank and gfg folder
adityaarakeri/Interview-solved pull request #81
Opened 2020-10-03 06:16 UTC by gitkp11

Added 
GeeksforGeeks/n-queens1.py 
HackerRank/Equal.py
HackerRank/Fibonacci Modified.py
HackerRank/Sherlock and Cost.py
HackerRank/The Coin Change Problem.py

2020-10-09 05:57 UTC, adityaarakeri requested changes
could you please rename your files according to the python `pep-8` convention
`file_name.py`

2020-10-19 04:08 UTC, gitkp11 reviewed
closes #81

2020-10-19 07:36 UTC, gitkp11 commented
close #81

2020-10-27 16:35 UTC, adityaarakeri approved these changes

2020-10-27 16:35 UTC, merged